export default {
  getUrl : (state) => state.base_url,
  getToken: (state) => state.token,
  getStatus: (state) => state.status,
  getAllTickets: (state) => state.allTickets,
  getCurrentTickets: (state) => state.currentTickets,
  getAllEmployees: (state) => state.allEmployees,
  getScannerList: (state) => state.scannerList,
  getPieData: (state) => state.dataPie,
  getBarData: (state) => state.dataBar,
  getBarData2: (state) => state.data2Bar,
  getBarTotal: (state) => state.totalBar,
  getBarTotal2: (state) => state.total2Bar,
  getPieTotal: (state) => state.totalPie,
  getPieLabel: (state) => state.labelsPie,
  getBarLabel: (state) => state.labelsBar,
  getTotalTicket: (state) => state.totalTickets,
  getTotalIncome: (state) => state.totalIncome,
  getDailyIncome: (state) => state.dailyIncome,
  getDailyTicket: (state) => state.dailyTickets,
  getEmployeeId: (state) => state.employeeId,
  getPriceList: (state) => state.priceList,
  getHoliday: (state) => state.holidays,
  getSlots: (state) => state.slots
}