export default {
    getData: (state) => state.maintopics,
    getDetail: (state) => state.detailTopic,
    getidmal: (state) => state.idmal,
    getideng: (state) => state.ideng, 
    getCommonIdMain: (state) => state.commonIdMain,
    getCommonIdSub: (state) => state.commonIdSub,
    getCommonIdSub2: (state) => state.commonIdSub2,
    getmalHeading: (state) => state.malHeading,
    getengHeading: (state) => state.engHeading,
    getmalSubHeading: (state) => state.malSubHeading,
    getengSubHeading: (state) => state.engSubHeading,
    getmalSub2Heading: (state) => state.malSub2Heading,
    getengSub2Heading: (state) => state.engSub2Heading,
    getsubidmal: (state) => state.subidmal,
    getsubideng: (state) => state.subideng,
    getsub2idmal: (state) => state.sub2idmal,
    getsub2ideng: (state) => state.sub2ideng,
    getSlots: (state) => state.slots,
    getLanguage: (state) => state.language,
    getLanguageList: (state) => state.languageList,
    getMedia: (state) => state.mediaType,
    getFirstSubData: (state) => state.firstSubData
};